#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Mon Jun 29 14:13:22 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class AuthDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AuthDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.deploy_banner_text = wx.StaticText(self, -1, "Deploy Application to Google")
        self.label_2 = wx.StaticText(self, -1, "Email:")
        self.name_text_ctrl = wx.TextCtrl(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, "Password:")
        self.password_text_ctrl = wx.TextCtrl(self, -1, "", style=wx.TE_PASSWORD)
        self.deploy_description = wx.StaticText(self, -1, "")
        self.cancel_button = wx.Button(self, -1, "Cancel")
        self.ok_button = wx.Button(self, -1, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AuthDialog.__set_properties
        self.SetTitle("Deploy Application to Google")
        self.SetSize((331, 191))
        self.deploy_banner_text.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.deploy_description.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Lucida Grande"))
        self.ok_button.SetFocus()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AuthDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(2, 2, 5, 5)
        sizer_1.Add(self.deploy_banner_text, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        grid_sizer_1.Add(self.label_2, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.name_text_ctrl, 1, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT, 5)
        grid_sizer_1.Add(self.label_3, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 5)
        grid_sizer_1.Add(self.password_text_ctrl, 1, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT, 5)
        grid_sizer_1.AddGrowableRow(0)
        grid_sizer_1.AddGrowableRow(1)
        grid_sizer_1.AddGrowableCol(1)
        sizer_1.Add(grid_sizer_1, 0, wx.ALL|wx.EXPAND, 0)
        sizer_1.Add(self.deploy_description, 0, wx.LEFT, 0)
        sizer_2.Add(self.cancel_button, 0, wx.ALL, 5)
        sizer_2.Add(self.ok_button, 0, wx.ALL, 5)
        sizer_1.Add(sizer_2, 0, wx.ALL|wx.ALIGN_RIGHT, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class AuthDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = AuthDialog(None, -1, "")
    app.SetTopWindow(dialog_1)
    dialog_1.Show()
    app.MainLoop()
