#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Mon Aug 24 21:53:36 2009

import wx

# begin wxGlade: extracode
import launcher

RUN_BUTTON = wx.NewId()
STOP_BUTTON = wx.NewId()
BROWSE_BUTTON = wx.NewId()
LOGS_BUTTON = wx.NewId()
SDK_CONSOLE_BUTTON = wx.NewId()
EDIT_BUTTON = wx.NewId()
DEPLOY_BUTTON = wx.NewId()
DASHBOARD_BUTTON = wx.NewId()
PLUS_BUTTON = wx.NewId()
MINUS_BUTTON = wx.NewId()
APP_SETTINGS_MENU = wx.NewId()
BROWSE_MENU = wx.NewId()
DASHBOARD_MENU = wx.NewId()
DEPLOY_MENU = wx.NewId()
LOGS_MENU = wx.NewId()
OPEN_EXTERNAL_EDITOR_MENU = wx.NewId()
OPEN_FILE_BROWSER_MENU = wx.NewId()
REMOVE_PROJECT_MENU = wx.NewId()
RUN_MENU = wx.NewId()
RUN_STRICT_MENU = wx.NewId()
SDK_CONSOLE_MENU = wx.NewId()
STOP_MENU = wx.NewId()
OPEN_SDK_MENU = wx.NewId()

import launcher

RUN_BUTTON = wx.NewId()
STOP_BUTTON = wx.NewId()
BROWSE_BUTTON = wx.NewId()
LOGS_BUTTON = wx.NewId()
SDK_CONSOLE_BUTTON = wx.NewId()
EDIT_BUTTON = wx.NewId()
DEPLOY_BUTTON = wx.NewId()
DASHBOARD_BUTTON = wx.NewId()
PLUS_BUTTON = wx.NewId()
MINUS_BUTTON = wx.NewId()

APP_SETTINGS_MENU = wx.NewId()
BROWSE_MENU = wx.NewId()
DASHBOARD_MENU = wx.NewId()
DEPLOY_MENU = wx.NewId()
LOGS_MENU = wx.NewId()
OPEN_EXTERNAL_EDITOR_MENU = wx.NewId()
OPEN_FILE_BROWSER_MENU = wx.NewId()
REMOVE_PROJECT_MENU = wx.NewId()
RUN_MENU = wx.NewId()
RUN_STRICT_MENU = wx.NewId()
SDK_CONSOLE_MENU = wx.NewId()
STOP_MENU = wx.NewId()
OPEN_SDK_MENU = wx.NewId()

# end wxGlade



class GenMainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GenMainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self._menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.newproject_menuitem = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "Create New Application...\tCtrl+N", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.newproject_menuitem)
        self.addproject_menuitem = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "Add Existing Application...\tCtrl+Shift+N", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.addproject_menuitem)
        self.removeproject_menuitem = wx.MenuItem(wxglade_tmp_menu, REMOVE_PROJECT_MENU, "Remove Project...\tCtrl+Del", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.removeproject_menuitem)
        wxglade_tmp_menu.AppendSeparator()
        self.open_sdk_menuitem = wx.MenuItem(wxglade_tmp_menu, OPEN_SDK_MENU, "Open SDK in Explorer...\tCtrl+Shift+D", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.open_sdk_menuitem)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_EXIT, "Exit\tCtrl-Q", "", wx.ITEM_NORMAL)
        self._menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_CUT, "Cut\tCtrl+X", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_COPY, "Copy\tCtrl+C", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_PASTE, "Paste\tCtrl+V", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_SELECTALL, "Select All\tCtrl+A", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        self.appsettings_menuitem = wx.MenuItem(wxglade_tmp_menu, APP_SETTINGS_MENU, "Application Settings...\tCtrl+I", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.appsettings_menuitem)
        wxglade_tmp_menu.AppendSeparator()
        self.open_edit_menuitem = wx.MenuItem(wxglade_tmp_menu, OPEN_EXTERNAL_EDITOR_MENU, "Open in External Editor\tCtrl+E", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.open_edit_menuitem)
        self.open_explorer_menuitem = wx.MenuItem(wxglade_tmp_menu, OPEN_FILE_BROWSER_MENU, "Open in Explorer\tCtrl+Shift+E", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.open_explorer_menuitem)
        wxglade_tmp_menu.AppendSeparator()
        self.preferences_menuitem = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "Preferences...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.preferences_menuitem)
        self._menubar.Append(wxglade_tmp_menu, "Edit")
        wxglade_tmp_menu = wx.Menu()
        self.run_menuitem = wx.MenuItem(wxglade_tmp_menu, RUN_MENU, "Run\tCtrl+R", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.run_menuitem)
        self.runstrict_menuitem = wx.MenuItem(wxglade_tmp_menu, RUN_STRICT_MENU, "Run Strict\tF5", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.runstrict_menuitem)
        self.stop_menuitem = wx.MenuItem(wxglade_tmp_menu, STOP_MENU, "Stop\tCtrl+Shift+R", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.stop_menuitem)
        self.browse_menuitem = wx.MenuItem(wxglade_tmp_menu, BROWSE_MENU, "Browse\tCtrl+B", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.browse_menuitem)
        self.log_console_menuitem = wx.MenuItem(wxglade_tmp_menu, LOGS_MENU, "Log Console\tCtrl+L", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.log_console_menuitem)
        self.sdk_console_menuitem = wx.MenuItem(wxglade_tmp_menu, SDK_CONSOLE_MENU, "SDK Console\tCtrl+K", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.sdk_console_menuitem)
        wxglade_tmp_menu.AppendSeparator()
        self.deploy_menuitem = wx.MenuItem(wxglade_tmp_menu, DEPLOY_MENU, "Deploy\tCtrl+D", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.deploy_menuitem)
        self.dashboard_menuitem = wx.MenuItem(wxglade_tmp_menu, DASHBOARD_MENU, "Dashboard\tCtrl+Shift+D", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.dashboard_menuitem)
        self._menubar.Append(wxglade_tmp_menu, "Control")
        wxglade_tmp_menu = wx.Menu()
        self.launcher_help_menuitem = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "Launcher Help", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.launcher_help_menuitem)
        self.app_engine_help_menuitem = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "App Engine Help", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.app_engine_help_menuitem)
        self.demos_menuitem = wx.MenuItem(wxglade_tmp_menu, 6000, "Demos", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.demos_menuitem)
        self.check_for_updates_menuitem = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "Check For Updates...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.check_for_updates_menuitem)
        wxglade_tmp_menu.AppendSeparator()
        self.about_launcher_menuitem = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "About Launcher...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.about_launcher_menuitem)
        self._menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self._menubar)
        # Menu Bar end
        
        # Tool Bar
        self._toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_3DBUTTONS|wx.TB_TEXT)
        self.SetToolBar(self._toolbar)
        self._toolbar.AddLabelTool(RUN_BUTTON, "Run", wx.Bitmap("./images/run.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self._toolbar.AddLabelTool(STOP_BUTTON, "Stop", wx.Bitmap("./images/stop.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self._toolbar.AddLabelTool(BROWSE_BUTTON, "Browse", wx.Bitmap("./images/browse.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self._toolbar.AddLabelTool(LOGS_BUTTON, "Logs", wx.Bitmap("./images/logs.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self._toolbar.AddLabelTool(SDK_CONSOLE_BUTTON, "SDK Console", wx.Bitmap("./images/sdk.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self._toolbar.AddSeparator()
        self._toolbar.AddLabelTool(EDIT_BUTTON, "Edit", wx.Bitmap("./images/edit.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self._toolbar.AddSeparator()
        self._toolbar.AddLabelTool(DEPLOY_BUTTON, "Deploy", wx.Bitmap("./images/deploy.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self._toolbar.AddLabelTool(DASHBOARD_BUTTON, "Dashboard", wx.Bitmap("./images/dashboard.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self._listctrl = launcher.ResizingListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnAddNewApp, self.newproject_menuitem)
        self.Bind(wx.EVT_MENU, self.OnAddApp, self.addproject_menuitem)
        self.Bind(wx.EVT_MENU, self.OnRemoveApp, self.removeproject_menuitem)
        self.Bind(wx.EVT_MENU, self.OnOpenSDK, self.open_sdk_menuitem)
        self.Bind(wx.EVT_MENU, self.OnExit, id=wx.ID_EXIT)
        self.Bind(wx.EVT_MENU, self.OnPaste, id=wx.ID_PASTE)
        self.Bind(wx.EVT_MENU, self.OnAppSettings, self.appsettings_menuitem)
        self.Bind(wx.EVT_MENU, self.OnEdit, self.open_edit_menuitem)
        self.Bind(wx.EVT_MENU, self.OnAppOpen, self.open_explorer_menuitem)
        self.Bind(wx.EVT_MENU, self.OnPreferences, self.preferences_menuitem)
        self.Bind(wx.EVT_MENU, self.OnRun, self.run_menuitem)
        self.Bind(wx.EVT_MENU, self.OnRunStrict, self.runstrict_menuitem)
        self.Bind(wx.EVT_MENU, self.OnStop, self.stop_menuitem)
        self.Bind(wx.EVT_MENU, self.OnBrowse, self.browse_menuitem)
        self.Bind(wx.EVT_MENU, self.OnLogs, self.log_console_menuitem)
        self.Bind(wx.EVT_MENU, self.OnSdkConsole, self.sdk_console_menuitem)
        self.Bind(wx.EVT_MENU, self.OnDeploy, self.deploy_menuitem)
        self.Bind(wx.EVT_MENU, self.OnDashboard, self.dashboard_menuitem)
        self.Bind(wx.EVT_MENU, self.OnHelp, self.launcher_help_menuitem)
        self.Bind(wx.EVT_MENU, self.OnAppEngineHelp, self.app_engine_help_menuitem)
        self.Bind(wx.EVT_MENU, self.OnDemos, self.demos_menuitem)
        self.Bind(wx.EVT_MENU, self.OnCheckForUpdates, self.check_for_updates_menuitem)
        self.Bind(wx.EVT_MENU, self.OnAbout, self.about_launcher_menuitem)
        self.Bind(wx.EVT_TOOL, self.OnRun, id=RUN_BUTTON)
        self.Bind(wx.EVT_TOOL, self.OnStop, id=STOP_BUTTON)
        self.Bind(wx.EVT_TOOL, self.OnBrowse, id=BROWSE_BUTTON)
        self.Bind(wx.EVT_TOOL, self.OnLogs, id=LOGS_BUTTON)
        self.Bind(wx.EVT_TOOL, self.OnSdkConsole, id=SDK_CONSOLE_BUTTON)
        self.Bind(wx.EVT_TOOL, self.OnEdit, id=EDIT_BUTTON)
        self.Bind(wx.EVT_TOOL, self.OnDeploy, id=DEPLOY_BUTTON)
        self.Bind(wx.EVT_TOOL, self.OnDashboard, id=DASHBOARD_BUTTON)
        self.Bind(wx.EVT_LIST_ITEM_DESELECTED, self.OnSelectionChange, self._listctrl)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.OnSelectionChange, self._listctrl)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GenMainFrame.__set_properties
        self.SetTitle("Google App Engine Launcher")
        self.SetSize((640, 456))
        self._toolbar.SetToolBitmapSize((32, 32))
        self._toolbar.Realize()
        self._listctrl.SetMinSize((600, 600))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GenMainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self._listctrl, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnAddNewApp(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnAddNewApp' not implemented!"
        event.Skip()

    def OnAddApp(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnAddApp' not implemented!"
        event.Skip()

    def OnRemoveApp(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnRemoveApp' not implemented!"
        event.Skip()

    def OnOpenSDK(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnOpenSDK' not implemented!"
        event.Skip()

    def OnExit(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnExit' not implemented!"
        event.Skip()

    def OnPaste(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnPaste' not implemented!"
        event.Skip()

    def OnAppSettings(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnAppSettings' not implemented!"
        event.Skip()

    def OnEdit(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnEdit' not implemented!"
        event.Skip()

    def OnAppOpen(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnAppOpen' not implemented!"
        event.Skip()

    def OnPreferences(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnPreferences' not implemented!"
        event.Skip()

    def OnRun(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnRun' not implemented!"
        event.Skip()

    def OnRunStrict(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnRunStrict' not implemented!"
        event.Skip()

    def OnStop(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnStop' not implemented!"
        event.Skip()

    def OnBrowse(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnBrowse' not implemented!"
        event.Skip()

    def OnLogs(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnLogs' not implemented!"
        event.Skip()

    def OnSdkConsole(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnSdkConsole' not implemented!"
        event.Skip()

    def OnDeploy(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnDeploy' not implemented!"
        event.Skip()

    def OnDashboard(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnDashboard' not implemented!"
        event.Skip()

    def OnHelp(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnHelp' not implemented!"
        event.Skip()

    def OnAppEngineHelp(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnAppEngineHelp' not implemented!"
        event.Skip()

    def OnDemos(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnDemos' not implemented!"
        event.Skip()

    def OnCheckForUpdates(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnCheckForUpdates' not implemented!"
        event.Skip()

    def OnAbout(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnAbout' not implemented!"
        event.Skip()

    def OnSelectionChange(self, event): # wxGlade: GenMainFrame.<event_handler>
        print "Event handler `OnSelectionChange' not implemented!"
        event.Skip()

# end of class GenMainFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    _project_frame = GenMainFrame(None, -1, "")
    app.SetTopWindow(_project_frame)
    _project_frame.Show()
    app.MainLoop()
