#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Mon Jun 22 20:01:37 2009

import wx

# begin wxGlade: extracode
#
# extra code
#

#
# extra code
#

# end wxGlade



class ProjectSettingsDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ProjectSettingsDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_3_staticbox = wx.StaticBox(self, -1, "Launch Settings")
        self.sizer_2_staticbox = wx.StaticBox(self, -1, "Application Settings")
        self.app_name_text_ctrl = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY)
        self.app_path_label = wx.StaticText(self, -1, "Application Path:")
        self.app_path_text_ctrl = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY)
        self.app_browse_button = wx.Button(self, -1, "Browse...")
        self.app_port_label = wx.StaticText(self, -1, "Port:", style=wx.ALIGN_RIGHT)
        self.app_port_text_ctrl = wx.TextCtrl(self, -1, "")
        self.full_flag_list_label = wx.StaticText(self, -1, "Extra Command Line Flags:")
        self.full_flag_list_text_ctrl = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.update_button = wx.Button(self, -1, "Update")
        self.cancel_button = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ProjectSettingsDialog.__set_properties
        self.SetTitle("Application Settings")
        self.app_name_text_ctrl.Enable(False)
        self.app_path_text_ctrl.Enable(False)
        self.app_browse_button.Enable(False)
        self.full_flag_list_text_ctrl.SetMinSize((320,120))
        self.update_button.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ProjectSettingsDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.HORIZONTAL)
        grid_sizer_2 = wx.FlexGridSizer(1, 3, 10, 10)
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 3, 10, 10)
        app_name_label = wx.StaticText(self, -1, "Application Name:")
        grid_sizer_1.Add(app_name_label, 0, wx.ALIGN_RIGHT, 10)
        grid_sizer_1.Add(self.app_name_text_ctrl, 0, wx.EXPAND, 10)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.app_path_label, 0, wx.ALIGN_RIGHT, 10)
        grid_sizer_1.Add(self.app_path_text_ctrl, 0, wx.EXPAND, 10)
        grid_sizer_1.Add(self.app_browse_button, 0, 0, 0)
        grid_sizer_1.Add(self.app_port_label, 0, wx.ALIGN_RIGHT, 10)
        grid_sizer_1.Add(self.app_port_text_ctrl, 0, 0, 10)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 10)
        sizer_1.Add(sizer_2, 0, wx.ALL|wx.EXPAND, 15)
        grid_sizer_2.Add(self.full_flag_list_label, 0, wx.ALIGN_RIGHT, 10)
        grid_sizer_2.Add(self.full_flag_list_text_ctrl, 1, wx.EXPAND, 0)
        grid_sizer_2.Add((84, 20), 0, 0, 0)
        grid_sizer_2.AddGrowableCol(1)
        sizer_3.Add(grid_sizer_2, 0, wx.EXPAND|wx.SHAPED, 10)
        sizer_1.Add(sizer_3, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 15)
        sizer_4.Add(self.update_button, 0, wx.RIGHT|wx.ALIGN_RIGHT, 10)
        sizer_4.Add(self.cancel_button, 0, wx.ALIGN_RIGHT, 0)
        sizer_1.Add(sizer_4, 0, wx.ALL|wx.ALIGN_RIGHT, 15)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class ProjectSettingsDialog


class AddExistingProjectDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AddExistingProjectDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_2_copy_staticbox = wx.StaticBox(self, -1, "Application Settings")
        self.app_path_label = wx.StaticText(self, -1, "Application Path:")
        self.app_path_text_ctrl = wx.TextCtrl(self, -1, "")
        self.app_browse_button = wx.Button(self, -1, "Browse...")
        self.app_port_label = wx.StaticText(self, -1, "Port:", style=wx.ALIGN_RIGHT)
        self.app_port_text_ctrl = wx.TextCtrl(self, -1, "")
        self.update_button = wx.Button(self, -1, "Add")
        self.cancel_button = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AddExistingProjectDialog.__set_properties
        self.SetTitle("Add Existing Application")
        self.app_path_text_ctrl.SetMinSize((300, 22))
        self.update_button.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AddExistingProjectDialog.__do_layout
        sizer_1_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_4_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy = wx.StaticBoxSizer(self.sizer_2_copy_staticbox, wx.VERTICAL)
        grid_sizer_1_copy = wx.FlexGridSizer(5, 3, 10, 10)
        grid_sizer_1_copy.Add(self.app_path_label, 0, wx.ALIGN_RIGHT, 10)
        grid_sizer_1_copy.Add(self.app_path_text_ctrl, 0, wx.EXPAND, 10)
        grid_sizer_1_copy.Add(self.app_browse_button, 0, 0, 0)
        grid_sizer_1_copy.Add(self.app_port_label, 0, wx.ALIGN_RIGHT, 10)
        grid_sizer_1_copy.Add(self.app_port_text_ctrl, 0, 0, 10)
        grid_sizer_1_copy.Add((20, 20), 0, 0, 0)
        grid_sizer_1_copy.Add((20, 20), 0, 0, 0)
        grid_sizer_1_copy.AddGrowableCol(1)
        sizer_2_copy.Add(grid_sizer_1_copy, 1, wx.EXPAND, 10)
        sizer_1_copy.Add(sizer_2_copy, 1, wx.ALL|wx.EXPAND, 15)
        sizer_4_copy.Add(self.update_button, 0, wx.RIGHT|wx.ALIGN_RIGHT, 10)
        sizer_4_copy.Add(self.cancel_button, 0, wx.ALIGN_RIGHT, 0)
        sizer_1_copy.Add(sizer_4_copy, 0, wx.ALL|wx.ALIGN_RIGHT, 15)
        self.SetSizer(sizer_1_copy)
        sizer_1_copy.Fit(self)
        self.Layout()
        # end wxGlade

# end of class AddExistingProjectDialog


class AddNewProjectDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AddNewProjectDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_2_copy_1_staticbox = wx.StaticBox(self, -1, "Application Settings")
        self.app_name_text_ctrl = wx.TextCtrl(self, -1, "")
        self.app_path_label = wx.StaticText(self, -1, "Parent Directory:")
        self.app_path_text_ctrl = wx.TextCtrl(self, -1, "")
        self.app_browse_button = wx.Button(self, -1, "Browse...")
        self.app_port_label_copy = wx.StaticText(self, -1, "Port:", style=wx.ALIGN_RIGHT)
        self.app_port_text_ctrl = wx.TextCtrl(self, -1, "")
        self.update_button = wx.Button(self, -1, "Create")
        self.cancel_button = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AddNewProjectDialog.__set_properties
        self.SetTitle("Add New Application")
        self.app_name_text_ctrl.SetMinSize((300, 22))
        self.update_button.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AddNewProjectDialog.__do_layout
        sizer_1_copy_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy_1 = wx.StaticBoxSizer(self.sizer_2_copy_1_staticbox, wx.VERTICAL)
        grid_sizer_1_copy_1 = wx.FlexGridSizer(4, 3, 10, 10)
        app_name_label = wx.StaticText(self, -1, "Application Name:")
        grid_sizer_1_copy_1.Add(app_name_label, 0, wx.ALIGN_RIGHT, 10)
        grid_sizer_1_copy_1.Add(self.app_name_text_ctrl, 0, wx.EXPAND, 10)
        grid_sizer_1_copy_1.Add((84, 20), 0, 0, 0)
        grid_sizer_1_copy_1.Add(self.app_path_label, 0, wx.ALIGN_RIGHT, 10)
        grid_sizer_1_copy_1.Add(self.app_path_text_ctrl, 0, wx.EXPAND, 10)
        grid_sizer_1_copy_1.Add(self.app_browse_button, 0, 0, 0)
        grid_sizer_1_copy_1.Add((84, 20), 0, 0, 0)
        grid_sizer_1_copy_1.Add((84, 20), 0, 0, 0)
        grid_sizer_1_copy_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1_copy_1.Add(self.app_port_label_copy, 0, wx.ALIGN_RIGHT, 10)
        grid_sizer_1_copy_1.Add(self.app_port_text_ctrl, 0, 0, 10)
        grid_sizer_1_copy_1.Add((84, 20), 0, 0, 0)
        grid_sizer_1_copy_1.Add((84, 20), 0, 0, 0)
        grid_sizer_1_copy_1.AddGrowableCol(1)
        sizer_2_copy_1.Add(grid_sizer_1_copy_1, 1, wx.EXPAND, 10)
        sizer_1_copy_1.Add(sizer_2_copy_1, 1, wx.ALL|wx.EXPAND, 15)
        sizer_4_copy_1.Add(self.update_button, 0, wx.RIGHT|wx.ALIGN_RIGHT, 10)
        sizer_4_copy_1.Add(self.cancel_button, 0, wx.ALIGN_RIGHT, 0)
        sizer_1_copy_1.Add(sizer_4_copy_1, 0, wx.ALL|wx.ALIGN_RIGHT, 15)
        self.SetSizer(sizer_1_copy_1)
        sizer_1_copy_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class AddNewProjectDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    app_settings_dialog = (None, -1, "")
    app.SetTopWindow(app_settings_dialog)
    app_settings_dialog.Show()
    app.MainLoop()
